---

- 

  hosts: database
  vars:
    remote_dir: /etc/ansible/facts.d
    facts_file: custom.fact
  tasks:
    - name: create Facts Dir on targets!
      file:
        path: "{{ remote_dir }}"
        state: directory
        recurse: yes
    - name: Copy custom.fact file
      copy:
        src: "{{ facts_file}}"
        dest: "{{ remote_dir }}"

    - name: gather the custom_fact
      setup:
        filter:
          - ansible_local
