---
# tasks file for sample-mysql
#  this line are just for practice
#
#- name: create pv, vg, 
# community.general.lvg:
#   pesise: 800
#   pvs: /dev/sdb
#   vg: vg_database

#- name: create lv in vg_database
#  community.general.lvol:
#   vg: vg_database
#   lv: lv_mysql

#- name: make file system for lv_mysql
# command: mkfs.xfs /dev/vg_database/lv_mysql && mount /mnt/mysql_backups

- name: add yum repository
  yum_repository:
    name: MySQL 8.0 Community Server
    description: MySQL 8.0 YUM Repo
    baseurl: http://repo.mysql.com/yum/mysql-8.0-community/el/6/$basearch/
    gpgkey: file:///etc/pki/rpm-gpg/RPM-GPG-KEY-mysql-2022 
    gpgcheck: yes
    enabled: yes


- name: import rpm gpg key
  command: rpm --import https://repo.mysql.com/RPM-GPG-KEY-mysql-2022


- name: Update DNF Package repository cache
  dnf:
    update_cache: True
- name: Install MySQL server on CentOS 8  
  dnf:
    name: mysql-server
    state: present
- name: Install MySQL client on CentOS 8
  dnf:
    name: mysql
    state: present
- name: Make sure mysqld service is running
  service:
    name: mysqld
    state: started
    enabled: True

- name: Install python3-PyMySQL library
  dnf:
    name: python3-PyMySQL
    state: present


  ######
  #- name: install mysql
  #package:
  #name: mysql-community-server  

# - name: enable firewall trafic
#   command: firewall-cmd --zone=public --add-port=3306/tcp --permanent && firewall-cmd --reload



- name:
  template:
    src: my.cnf.j2
    dest: /etc/my.cnf

- name:
  service:
    name: mysqld
    state: restarted
    enabled: yes

- name: Set MySQL root Password
  mysql_user:
    login_host: 'localhost'
    login_user: 'root'
    login_password: ''
    name: 'root'
    password: "{{ database_password  }}"
    state: present


